"""empty message

Revision ID: 89f2f85474c4
Revises: 7cb6d41a88d0
Create Date: 2022-12-03 05:12:06.355771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f2f85474c4'
down_revision = '7cb6d41a88d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('my_user', sa.String(length=150), nullable=False),
    sa.Column('itemname', sa.String(length=300), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('my_user', name=op.f('uq_item_my_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
